cask_args appdir: '/Applications'

tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'caskroom/fonts'
tap 'homebrew/versions'

brew 'ack'
brew 'ansible'
# zsh plugin manager
brew 'antigen'
brew 'bash'
brew 'bash-completion'
brew 'bazaar'
brew 'bison'
brew 'coreutils'
brew 'cowsay'
brew 'findutils'
brew 'fortune'
brew 'gist'
brew 'git-extras'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go'
brew 'graphviz'
brew 'grc'
brew 'htop-osx'
brew 'hub'
brew 'id3tool'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
# Requires quartz
#brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'mercurial'
brew 'nmap'
brew 'homebrew/versions/node4-lts'
brew 'nvm'
brew 'readline'
brew 'openvpn'
brew 'packer'
brew 'postgresql'
brew 'pv'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'ssh-copy-id'
brew 'sqlite'
brew 'terminal-notifier'
brew 'tmux'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'adium'
cask 'atom'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'google-hangouts'
# Screen-shotter
cask 'gyazo'
cask 'handbrake'
# Hex editor
cask 'hex-fiend'
# Pandora client
cask 'hermes'
cask 'iterm2'
cask 'macvim'
cask 'omnigraffle'
# No available cask warning
#cask 'remote-desktop-connection'
# Graphics Editor
cask 'seashore'
cask 'slack'
cask 'skitch'
cask 'skype'
cask 'sourcetree'
cask 'spotify'
cask 'teamviewer'
# Torrent Client
cask 'transmission'
# VPN service
cask 'tunnelbear'
# General purpose decompression app
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'flux'

# Productivity
cask 'alfred'

# Quick Look plugins
cask 'animated-gif-quicklook'
cask 'betterzipql'
cask 'epubquicklook'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'quicknfo'
cask 'suspicious-package'
cask 'webpquicklook'

# Color pickers
cask 'colorpicker-developer'
cask 'colorpicker-skalacolor'

# Fonts
cask 'font-droid-sans'
cask 'font-droid-sans-mono'
cask 'font-inconsolata'
# 404
#cask 'font-liberation-mono'
cask 'font-liberation-sans'
cask 'font-meslo-lg'
cask 'font-nixie-one'
cask 'font-pt-mono'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-ubuntu'

# Phase2
tap 'phase2/devtools'
cask 'caskroom/cask/flowdock'
cask 'caskroom/cask/tunnelblick'
brew 'phase2/devtools/devtools'
brew 'phase2/devtools/docker'
brew 'phase2/devtools/docker-compose'
brew 'phase2/devtools/docker-machine'
